name: Building Docker container
on:
  push:
    branches:
      - master
      - develop
      - docker_build_workflow
  pull_request:
    branches:
      - master
      - develop
    tags:
      - v*
jobs:
  build_docker:
    runs-on: ubuntu-latest
    name: Build docker container
    steps:
      - name: Fetch source code
        uses: actions/checkout@v2
        id: fetch-source
      - name: man find
        run: man find > find.txt
      - name: show folder
        run: ls -l
      - name: upload help
        uses: actions/upload-artifact@v2
        with:
          name: find_help
          path: find.txt
      - name: permissions
        run: chmod +x .github/workflows/find_test.sh
      - name: run find
        run: .github/workflows/find_test.sh
