name: Find
on:
  push:
    branches:
      - master
      - develop
      - docker_build_workflow
  pull_request:
    branches:
      - master
      - develop
    tags:
      - v*
jobs:
  build_docker:
    runs-on: ubuntu-latest
    name: Find
    strategy:
      matrix:
        apps: [pylint, pytest]
        include:
          - apps: pylint
            foo: boo
          - apps: pytest
            foo: zoo
    steps:
      - name: Fetch source code
        uses: actions/checkout@v2
        id: fetch-source
      - name: man find
        run: man find > find.txt
      - name: show folder
        run: ls -l
      - name: permissions
        run: chmod +x .github/workflows/find_test.sh
      - name: run find
        run: .github/workflows/find_test.sh
      - name: check using counts
        run: |
             X=$(find . | grep 'orthomosaic_mask\.tif' | wc -l) && echo "|${X}|"
             echo $X
             if [[ "$X" == "64" ]]; then echo "All found"; else echo "Missing"; exit 2; fi
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"
        if: { ${{ matrix.foo }} == "zoo" }
